[tool.poetry]
name = "leetcode"
version = "0.1.0"
description = ""
authors = ["TurtleSmoke <46165291+TuWG@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
black = "^23.1.0"
pylint = "^2.16.3"
python-leetcode-runner = "^1.0.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
